[workspace.package]
version = "0.2.0"
authors = ["Sascha"]
description = "A stress test for PyTorch CPU and GPU"
homepage = "https://github.com/sascharo/rust-pytorch"

[workspace]
members = [
    "stress-test"
]
default-members = [
    "stress-test"
]
# exclude = []
resolver = "2"
