name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Install & set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-musl

    - name: Install C++ libraries
      run: sudo apt-get install -y libstdc++-10-dev


    - name: Download and install libtorch
      run: |
        wget https://download.pytorch.org/libtorch/cu124/libtorch-shared-with-deps-2.4.0%2Bcu124.zip
        sudo unzip libtorch-shared-with-deps-2.4.0+cu124.zip -d /usr/local
        echo "/usr/local/libtorch/lib" | sudo tee /etc/ld.so.conf.d/libtorch.conf
        sudo ldconfig

    - name: Set environment variables
      run: |
        echo "LIBTORCH=/usr/local/libtorch" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=/usr/local/libtorch/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Cache cargo registry
      uses: actions/cache@main
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache cargo index
      uses: actions/cache@main
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-

    - name: Cache cargo build
      uses: actions/cache@main
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-

    - name: Build
      run: cargo build --verbose

    # - name: Install dependent C++ libraries
    #   run: sudo apt-get update && sudo apt-get install -y wget unzip libstdc++-10-dev
    
    # - name: Download and install libtorch
    #   run: |
    #     wget https://download.pytorch.org/libtorch/cu124/libtorch-shared-with-deps-2.4.0%2Bcu124.zip
    #     sudo unzip libtorch-shared-with-deps-2.4.0+cu124.zip -d /usr/local
    #     echo "/usr/local/libtorch/lib" | sudo tee /etc/ld.so.conf.d/libtorch.conf
    #     sudo ldconfig

    # - name: Set environment variables
    #   run: |
    #     echo "LIBTORCH=/usr/local/libtorch" >> $GITHUB_ENV
    #     echo "LD_LIBRARY_PATH=/usr/local/libtorch/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    # - name: Build
    #   env:
    #     LIBTORCH: /usr/local/libtorch
    #     LD_LIBRARY_PATH: /usr/local/libtorch/lib:$LD_LIBRARY_PATH
    #   run: cargo build --verbose

    # - name: Run tests
    #   env:
    #     LIBTORCH: /usr/local/libtorch
    #     LD_LIBRARY_PATH: /usr/local/libtorch/lib:$LD_LIBRARY_PATH
    #   run: cargo test --verbose

  # stress-test:
  #   runs-on: windows-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@main
